wandb: Currently logged in as: longnd (aiotlab). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.7 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in /home/ace15032jo/Projects/repo2/SampleSelection_easyFL/wandb/run-20230111_022000-19xzfpog
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fedalgo7_prox_ratio_1.0_C_0.5_config2_inverse
wandb: ‚≠êÔ∏è View project at https://wandb.ai/aiotlab/Abnormal_Data_FL
wandb: üöÄ View run at https://wandb.ai/aiotlab/Abnormal_Data_FL/runs/19xzfpog
2023-01-11 02:20:02,164 fflow.py initialize [line:267] INFO Using Logger in `utils.logger.basic_logger`
2023-01-11 02:20:02,164 fflow.py initialize [line:268] INFO Initializing fedtask: pill_classification
2023-01-11 02:20:02,710 fflow.py initialize [line:284] INFO Using model `resnet18` in `benchmark.pill_classification.model.resnet18` as the globally shared model.
2023-01-11 02:20:02,716 fflow.py initialize [line:312] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2023-01-11 02:20:08,819 fflow.py initialize [line:332] INFO Initializing Clients: 10 clients of `algorithm.fedalgo7_prox.Client` being created.
2023-01-11 02:20:08,820 fflow.py initialize [line:353] INFO Initializing Server: 1 server of `algorithm.fedalgo7_prox.Server` being created.
2023-01-11 02:20:08,843 fflow.py initialize [line:366] INFO Ready to start.
2023-01-11 02:20:08,843 fedbase.py run [line:63] INFO --------------Round 1--------------
2023-01-11 02:20:14,149 basic_logger.py show_current_output [line:147] INFO test_accuracy                 0.0130
2023-01-11 02:20:14,150 basic_logger.py show_current_output [line:147] INFO test_loss                     4.5173
2023-01-11 02:20:14,150 basic_logger.py time_end [line:77] INFO Eval Time Cost:               5.3070s
2023-01-11 02:20:14,155 fedalgo7_prox.py iterate [line:112] INFO Selected clients : [1, 2, 7, 3, 5]
wandb: ERROR Failed to sample metric: process no longer exists (pid=128269)
