2022-12-21 19:37:48,828 fflow.py initialize [line:259] INFO Using Logger in `utils.logger.basic_logger`
2022-12-21 19:37:48,832 fflow.py initialize [line:260] INFO Initializing fedtask: pill_classification
2022-12-21 19:37:48,952 fflow.py initialize [line:276] INFO Using model `resnet18` in `benchmark.pill_classification.model.resnet18` as the globally shared model.
2022-12-21 19:37:48,955 fflow.py initialize [line:304] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
Using cache found in /home/aiotlabws/.cache/torch/hub/pytorch_vision_v0.10.0
2022-12-21 19:38:00,714 fflow.py initialize [line:324] INFO Initializing Clients: 10 clients of `algorithm.fedalgo1_fedprox.Client` being created.
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 21, in main
    server = flw.initialize(option)
  File "/mnt/disk2/ndlong/easyFL/utils/fflow.py", line 331, in initialize
    clients = [
  File "/mnt/disk2/ndlong/easyFL/utils/fflow.py", line 332, in <listcomp>
    Client(
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1_fedprox.py", line 141, in __init__
    self.init_algo_para({'mu':0.1})
AttributeError: 'Client' object has no attribute 'init_algo_para'