2022-12-21 21:52:43,806 fflow.py initialize [line:259] INFO Using Logger in `utils.logger.basic_logger`
2022-12-21 21:52:43,806 fflow.py initialize [line:260] INFO Initializing fedtask: pill_classification
2022-12-21 21:52:43,941 fflow.py initialize [line:276] INFO Using model `resnet18` in `benchmark.pill_classification.model.resnet18` as the globally shared model.
2022-12-21 21:52:43,950 fflow.py initialize [line:304] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2022-12-21 21:52:50,998 fflow.py initialize [line:324] INFO Initializing Clients: 10 clients of `algorithm.fedalgo1_fedprox.Client` being created.
2022-12-21 21:52:50,999 fflow.py initialize [line:345] INFO Initializing Server: 1 server of `algorithm.fedalgo1_fedprox.Server` being created.
2022-12-21 21:52:50,999 fflow.py initialize [line:358] INFO Ready to start.
2022-12-21 21:52:50,999 fedbase.py run [line:61] INFO --------------Round 1--------------
2022-12-21 21:52:55,879 basic_logger.py show_current_output [line:134] INFO test_accuracy                 0.0130
2022-12-21 21:52:55,879 basic_logger.py show_current_output [line:134] INFO test_loss                     4.5173
2022-12-21 21:52:55,879 basic_logger.py time_end [line:74] INFO Eval Time Cost:               4.8799s
2022-12-21 21:52:55,885 fedalgo1_fedprox.py iterate [line:20] INFO Selected clients : [1, 2]
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2022-12-21 21:55:34,512 basic_logger.py time_end [line:74] INFO Time Cost:                    163.5130s
2022-12-21 21:55:34,513 fedbase.py run [line:61] INFO --------------Round 2--------------
Total samples which participate training : 1495 samples
2022-12-21 21:55:39,348 basic_logger.py show_current_output [line:134] INFO test_accuracy                 0.2390
2022-12-21 21:55:39,348 basic_logger.py show_current_output [line:134] INFO test_loss                     3.3605
2022-12-21 21:55:39,349 basic_logger.py time_end [line:74] INFO Eval Time Cost:               4.8358s
2022-12-21 21:55:39,362 fedalgo1_fedprox.py iterate [line:20] INFO Selected clients : [3, 0]
Using cache found in /home/ace15032jo/.cache/torch/hub/pytorch_vision_v0.10.0
2022-12-21 21:57:58,389 basic_logger.py time_end [line:74] INFO Time Cost:                    143.8765s
2022-12-21 21:57:58,390 fedbase.py run [line:61] INFO --------------Round 3--------------
Total samples which participate training : 1090 samples
2022-12-21 21:58:02,237 main.py main [line:27] ERROR Exception Logged
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/algorithm/fedbase.py", line 65, in run
    flw.logger.log_once()
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/utils/logger/basic_logger.py", line 202, in log_once
    test_metric = self.server.test()
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/algorithm/fedbase.py", line 297, in test
    return self.calculator.test(
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/benchmark/toolkits.py", line 690, in test
    for batch_id, batch_data in enumerate(data_loader):
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 230, in __getitem__
    sample = self.loader(path)
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 269, in default_loader
    return pil_loader(path)
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 248, in pil_loader
    img = Image.open(f)
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/PIL/Image.py", line 3140, in open
    prefix = fp.read(16)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/main.py", line 24, in main
    server.run()
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/algorithm/fedbase.py", line 65, in run
    flw.logger.log_once()
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/utils/logger/basic_logger.py", line 202, in log_once
    test_metric = self.server.test()
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/algorithm/fedbase.py", line 297, in test
    return self.calculator.test(
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/benchmark/toolkits.py", line 690, in test
    for batch_id, batch_data in enumerate(data_loader):
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 230, in __getitem__
    sample = self.loader(path)
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 269, in default_loader
    return pil_loader(path)
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 248, in pil_loader
    img = Image.open(f)
  File "/home/ace15032jo/venv/pytorch+horovod/lib/python3.10/site-packages/PIL/Image.py", line 3140, in open
    prefix = fp.read(16)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/main.py", line 33, in <module>
    main()
  File "/home/ace15032jo/Projects/SampleSelection_easyFL/main.py", line 28, in main
    raise RuntimeError
RuntimeError