2022-12-21 10:53:40,672 fflow.py initialize [line:255] INFO Using Logger in `utils.logger.basic_logger`
2022-12-21 10:53:40,675 fflow.py initialize [line:256] INFO Initializing fedtask: pill_classification
2022-12-21 10:53:40,750 fflow.py initialize [line:272] INFO Using model `resnet18` in `benchmark.pill_classification.model.resnet18` as the globally shared model.
2022-12-21 10:53:40,752 fflow.py initialize [line:298] INFO Using sampler `threshold_sampler` in `sampler.threshold_sampler` as the globally shared model.
Using cache found in /home/aiotlabws/.cache/torch/hub/pytorch_vision_v0.10.0
2022-12-21 10:53:48,867 fflow.py initialize [line:318] INFO Initializing Clients: 10 clients of `algorithm.fedalgo1.Client` being created.
2022-12-21 10:53:48,869 fflow.py initialize [line:339] INFO Initializing Server: 1 server of `algorithm.fedalgo1.Server` being created.
2022-12-21 10:53:48,869 fflow.py initialize [line:352] INFO Ready to start.
2022-12-21 10:53:48,869 fedbase.py run [line:61] INFO --------------Round 1--------------
2022-12-21 10:53:58,872 basic_logger.py show_current_output [line:134] INFO test_accuracy                 0.0130
2022-12-21 10:53:58,873 basic_logger.py show_current_output [line:134] INFO test_loss                     4.5173
2022-12-21 10:53:58,873 basic_logger.py time_end [line:74] INFO Eval Time Cost:               10.0034s
2022-12-21 10:53:58,874 fedalgo1.py iterate [line:21] INFO Selected clients : [1, 2]
Total samples which participate training : 1495 samples
> /mnt/disk2/ndlong/easyFL/algorithm/fedbase.py(84)run()
     83                 breakpoint()
---> 84                 utils.fmodule.save_json(self.log_file, f'{self.option["log_result_path"]}/{self.option["group_name"]}',self.option["session_name"])
     85                 utils.fmodule.LOG_DICT = {}
Using cache found in /home/aiotlabws/.cache/torch/hub/pytorch_vision_v0.10.0
2022-12-21 11:09:49,778 basic_logger.py time_end [line:74] INFO Time Cost:                    960.9083s
2022-12-21 11:09:49,779 fedbase.py run [line:84] INFO --------------Round 2--------------
2022-12-21 11:09:58,187 basic_logger.py show_current_output [line:134] INFO test_accuracy                 0.2701
2022-12-21 11:09:58,187 basic_logger.py show_current_output [line:134] INFO test_loss                     3.3426
2022-12-21 11:09:58,187 basic_logger.py time_end [line:74] INFO Eval Time Cost:               8.4048s
2022-12-21 11:09:58,188 fedalgo1.py iterate [line:21] INFO Selected clients : [3, 0]
Program interrupted. (Use 'cont' to resume).
> /mnt/disk2/ndlong/easyFL/sampler/base_sampler.py(23)cal_gnorm()
     22         total_norm = 0
---> 23         for p in model.parameters():
     24             param_norm = p.grad.detach().data.norm(2)
2022-12-21 11:12:47,380 main.py main [line:24] ERROR Exception Logged
Traceback (most recent call last):
  File "main.py", line 24, in main
    server.run()
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedbase.py", line 84, in run
    utils.fmodule.save_json(self.log_file, f'{self.option["log_result_path"]}/{self.option["group_name"]}',self.option["session_name"])
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 22, in iterate
    threshold_score = self.cal_threshold(self.selected_clients)
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 129, in cal_threshold
    self.calculate_importance(selected_clinets)
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 115, in calculate_importance
    cpkqs = [self.communicate_score_with(id) for id, c in enumerate(self.clients)]
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 115, in <listcomp>
    cpkqs = [self.communicate_score_with(id) for id, c in enumerate(self.clients)]
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 126, in communicate_score_with
    return self.clients[client_id].reply_score(svr_pkg)
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 153, in reply_score
    self.calculate_importance(copy.deepcopy(model))
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 145, in calculate_importance
    _, score_list_on_cl = utils.fmodule.Sampler.cal_score(
  File "/mnt/disk2/ndlong/easyFL/sampler/threshold_sampler.py", line 15, in cal_score
    list_score, list_idx = self.cal_gnorm_model_weight(
  File "/mnt/disk2/ndlong/easyFL/sampler/base_sampler.py", line 46, in cal_gnorm_model_weight
    score_ = self.cal_gnorm(model)
  File "/mnt/disk2/ndlong/easyFL/sampler/base_sampler.py", line 23, in cal_gnorm
    for p in model.parameters():
  File "/mnt/disk2/ndlong/easyFL/sampler/base_sampler.py", line 23, in cal_gnorm
    for p in model.parameters():
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
Traceback (most recent call last):
  File "main.py", line 24, in main
    server.run()
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedbase.py", line 84, in run
    utils.fmodule.save_json(self.log_file, f'{self.option["log_result_path"]}/{self.option["group_name"]}',self.option["session_name"])
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 22, in iterate
    threshold_score = self.cal_threshold(self.selected_clients)
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 129, in cal_threshold
    self.calculate_importance(selected_clinets)
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 115, in calculate_importance
    cpkqs = [self.communicate_score_with(id) for id, c in enumerate(self.clients)]
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 115, in <listcomp>
    cpkqs = [self.communicate_score_with(id) for id, c in enumerate(self.clients)]
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 126, in communicate_score_with
    return self.clients[client_id].reply_score(svr_pkg)
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 153, in reply_score
    self.calculate_importance(copy.deepcopy(model))
  File "/mnt/disk2/ndlong/easyFL/algorithm/fedalgo1.py", line 145, in calculate_importance
    _, score_list_on_cl = utils.fmodule.Sampler.cal_score(
  File "/mnt/disk2/ndlong/easyFL/sampler/threshold_sampler.py", line 15, in cal_score
    list_score, list_idx = self.cal_gnorm_model_weight(
  File "/mnt/disk2/ndlong/easyFL/sampler/base_sampler.py", line 46, in cal_gnorm_model_weight
    score_ = self.cal_gnorm(model)
  File "/mnt/disk2/ndlong/easyFL/sampler/base_sampler.py", line 23, in cal_gnorm
    for p in model.parameters():
  File "/mnt/disk2/ndlong/easyFL/sampler/base_sampler.py", line 23, in cal_gnorm
    for p in model.parameters():
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/mnt/disk1/anaconda3/envs/longnd/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 24, in main
    server.run()
RuntimeError
If you suspect this is an IPython 8.3.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True